const fs = require('fs');

const medical = {
  "medical": {
    "symptomsList": {
      "headache": "Головная боль",
      "fatigue": "Усталость",
      "bloating": "Вздутие",
      "templePressure": "Давление в висках",
      "nausea": "Тошнота",
      "stress": "Стресс",
      "insomnia": "Бессонница"
    },
    "errorSavingSymptoms": "Ошибка сохранения симптомов",
    "errorGeneratingInsights": "Ошибка генерации инсайтов",
    "symptomsRegistration": "Регистрация симптомов",
    "symptomsDescription": "Опишите ваше самочувствие сегодня",
    "frequentSymptoms": "Частые симптомы",
    "customSymptomPlaceholder": "Ваш симптом...",
    "add": "Добавить",
    "selected": "Выбрано",
    "delete": "Удалить",
    "strengthLabel": "Сила:",
    "saveDay": "Сохранить день",
    "successfullySaved": "Успешно сохранено",
    "aiCorrelationAnalysis": "AI Корреляционный Анализ",
    "aiCorrelationDescription": "Анализ связей между вашими симптомами",
    "analyzing": "Анализируем...",
    "generateInsights": "Сгенерировать Инсайты",
    "confidenceLabel": "Уверенность",
    "noCorrelationsFound": "Корреляций не найдено",
    "onlyOneDocument": "Только один документ",
    "documentTooLarge": "Документ слишком большой",
    "maxTenPhotos": "Максимум 10 фото",
    "photosTooLarge": "Фотографии слишком большие",
    "uploadAriaLabel": "Загрузить",
    "dragDropTitle": "Перетащите файлы сюда",
    "dragDropSubtitle": "Или кликните для выбора",
    "acceptedFormats": "Поддерживаемые форматы: JPG, PNG, PDF",
    "or": "или",
    "takePhoto": "Сделать фото",
    "analyzingDocument": "Анализируем документ...",
    "reportGenerated": "Отчет сгенерирован",
    "uploadNewResults": "Загрузить новые результаты",
    "uploadNewResultsSub": "Загрузите анализы для AI расшифровки",
    "addNewAnalysis": "Добавить анализ",
    "processingError": "Ошибка обработки",
    "invalidImageFormat": "Неверный формат изображения",
    "analysisError": "Ошибка анализа",
    "nailsAnalysisTitle": "Анализ ногтей",
    "nailsPhoto": "Фото ногтей",
    "nailsPhotoZoomed": "Увеличенное фото ногтей",
    "diagnosticError": "Ошибка диагностики",
    "noBiomarkersFound": "Биомаркеры не найдены",
    "refreshFailed": "Ошибка обновления",
    "deleteConfirm": "Подтвердите удаление",
    "deleteFailed": "Ошибка удаления",
    "nailsAnalysis": "Анализ ногтей",
    "tongueAnalysis": "Анализ языка",
    "skinAnalysis": "Анализ кожи",
    "uploadingFiles": "Загрузка файлов...",
    "requestAccepted": "Запрос принят",
    "aiAnalyzing": "AI Анализирует...",
    "processing": "Обработка...",
    "gpt4oProcessing": "Обработка GPT-4o...",
    "processingTime": "Время обработки",
    "analysisResults": "Результаты анализа",
    "markersCount": "Количество маркеров",
    "contextLabel": "Контекст",
    "normLabel": "Норма",
    "noData": "Нет данных",
    "refreshing": "Обновление...",
    "refreshMarkers": "Обновить маркеры",
    "generateReport": "Сгенерировать отчет",
    "unsavedChanges": "Несохраненные изменения",
    "unsavedChangesSub": "Сохраните изменения перед продолжением",
    "verifyData": "Проверьте данные",
    "aiMedicalAnalysis": "AI Медицинский Анализ",
    "noAnalysesFound": "Анализы не найдены",
    "preparingReport": "Подготовка отчета...",
    "deepAnalysisTime": "Глубокий анализ...",
    "reportFailed": "Ошибка генерации отчета",
    "tryAgain": "Попробовать снова",
    "diagnosisHistory": "История диагнозов",
    "session": "Сессия",
    "deleteSelectedReport": "Удалить выбранный отчет",
    "diagnosticReportTitle": "Диагностический отчет",
    "premiumAnalysis": "Премиум Анализ",
    "markersAssessment": "Оценка маркеров",
    "refLabel": "Референс",
    "identifiedPatterns": "Выявленные паттерны",
    "markersLabel": "Маркеры",
    "priorityActions": "Приоритетные действия",
    "recommendedTests": "Рекомендованные тесты",
    "dietaryRecommendations": "Диетические рекомендации",
    "targetMarkersLabel": "Целевые маркеры",
    "T": "T",
    "profile-updated": "Профиль обновлен",
    "@": "@",
    "OCR для скриншотов Garmin / Whoop — скоро!": "OCR для скриншотов Garmin / Whoop — скоро!",
    "OCR для скриншотов весов — скоро!": "OCR для скриншотов весов — скоро!",
    "OCR для Nutrisense / Levels — скоро!": "OCR для Nutrisense / Levels — скоро!",
    "OCR для скриншотов Apple Health — скоро!": "OCR для скриншотов Apple Health — скоро!",
    "refRange": "Референс",
    "confidence": "Уверенность",
    "close": "Закрыть",
    "fresh": "Свежий",
    "detectedMarkers": "Обнаруженные маркеры",
    "noDeviations": "Отклонений не обнаружено",
    "aiInterpretation": "AI Интерпретация",
    "zoomedIn": "Увеличено",
    "symptoms": "Симптомы"
  }
};

const filePath = 'src/i18n/messages/ru.json';
const ru = JSON.parse(fs.readFileSync(filePath, 'utf8'));

// Inject the new medical namespace
ru.medical = medical.medical;

fs.writeFileSync(filePath, JSON.stringify(ru, null, 2));
console.log('Successfully injected medical namespace to ru.json');
